# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!

target ‘CIProject’ do
    pod 'MBProgressHUD'
    pod 'Reachability'
    pod 'MagicalRecord'
    pod 'PureLayout'
    pod 'SVPullToRefresh'
    pod 'PasscodeLock'
end



